packages:
  - "apps/api"
  - "apps/packages/*"
  - "apps/workers/*"
  - "apps/web"
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  msw: true
  prisma: true
  sharp: true
