name: Playwright Tests
run-name: ${{ github.actor }} performing end to end tests
on:
  push:
    branches: [ main, master ]
    paths:
      - "apps/web/**"
  pull_request:
    branches: [ main, master ]
    paths:
      - "apps/web/**"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-workspace
    - name: Install Playwright Browsers
      run: pnpm --filter ./apps/web exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm --filter ./apps/web exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: apps/web/playwright-report/
        retention-days: 30
